import { FamilyMember } from './types';

export const MURATOV_DATA: Record<string, FamilyMember> = {
  '1': {
    id: '1',
    firstName: 'Mahmudjon',
    lastName: 'xoji ota',
    birthYear: 1855,
    deathYear: 'Aniq emas',
    gender: 'male',
    parents: [],
    children: ['2'],
    spouses: [],
    bio: 'Muratovlar sulolasining ma\'lum bo\'lgan eng katta ajdodi.',
    occupation: 'Dehqon, Ma\'rifatparvar',
  },
  '2': {
    id: '2',
    firstName: 'Murodilloxon',
    lastName: 'xoji ota',
    birthYear: 1880,
    deathYear: 'Aniq emas',
    gender: 'male',
    parents: ['1'],
    children: ['3'],
    spouses: [],
    bio: 'Mahmudjon xoji otaning o\'g\'li.',
  },
  '3': {
    id: '3',
    firstName: 'Ergashali',
    lastName: 'xoji ota',
    birthYear: 1904,
    deathYear: 1995,
    gender: 'male',
    parents: ['2'],
    children: ['4', '5', '6', '7', '8', '9', '10', '13'],
    spouses: [],
    occupation: 'Jamoat arbobi',
    bio: 'Ergashali xoji ota o‘z davrining taniqli jamoat arbobi, el-yurt ardog‘idagi inson bo‘lgan. U o‘zining adolati, donoligi va tashkilotchilik qobiliyati bilan ko‘pchilikka namuna bo‘lgan, oila a’zolarini ham shu ruhda tarbiyalagan.',
  },
  '4': {
    id: '4',
    firstName: 'Turdivoy',
    lastName: 'Muratov',
    birthYear: 1939,
    deathYear: 2002,
    gender: 'male',
    parents: ['3'],
    children: [],
    spouses: [],
    bio: 'Turdivoy Muratov oilaning to‘ng‘ich farzandi sifatida mas’uliyatli, mehnatsevar va sabotli inson bo‘lgan. U ajdodlar an’analarini hurmat qilgan va atrofdagilarga o‘zining bosiqligi bilan tanilgan.',
  },
  '5': {
    id: '5',
    firstName: 'Mahbubahon',
    lastName: 'Muratova',
    birthYear: 1945,
    deathYear: 2008,
    gender: 'female',
    parents: ['3'],
    children: [],
    spouses: [],
    bio: 'Mahbubahon Muratova o‘zining latofati, mehnatsevarligi va oilaga bo‘lgan sadoqati bilan ajralib turgan oqila ayollardan biri bo‘lgan.',
  },
  '6': {
    id: '6',
    firstName: 'Habibahon',
    lastName: 'Ergashova',
    birthYear: 1950,
    deathYear: 2012,
    gender: 'female',
    parents: ['3'],
    children: [],
    spouses: [],
    bio: 'Habibahon Ergashova nihoyatda samimiy, g‘amxo‘r va sabr-toqatli inson bo‘lib, yaqinlarining hurmat-e’tiborini qozongan.',
  },
  '7': {
    id: '7',
    firstName: 'Nematjon',
    lastName: 'Muratov',
    birthYear: 1955,
    deathYear: 2022,
    gender: 'male',
    parents: ['3'],
    children: [],
    spouses: [],
    bio: 'Nematjon Muratov o‘z kasbining ustasi, halol va vijdonli mehnat qilgan insonlardan biri sifatida xotirlanadi.',
  },
  '8': {
    id: '8',
    firstName: 'Izzatilla',
    lastName: 'Muratov',
    birthYear: 1957,
    deathYear: 2020,
    gender: 'male',
    parents: ['3'],
    children: [],
    spouses: [],
    bio: 'Izzatilla Muratov jonkuyarligi, chaqqonligi va har qanday vaziyatda ham do‘stlariga yordamga shayligi bilan ajralib turgan.',
  },
  '9': {
    id: '9',
    firstName: 'Asadillo',
    lastName: 'Muratov',
    birthYear: 1959,
    gender: 'male',
    parents: ['3'],
    children: [],
    spouses: [],
    occupation: 'kafil chiqaralla',
    bio: 'Asadillo Muratov o‘zining ishbilarmonligi va har qanday murakkab vazifani bajarishda namoyon etadigan qat’iyati bilan tanilgan.',
  },
  '10': {
    id: '10',
    firstName: 'Abdulbori',
    lastName: 'Muratov',
    birthYear: 1962,
    gender: 'male',
    parents: ['3'],
    children: ['11a', '11b', '11c', '11d', '11e'],
    spouses: ['s10'],
    occupation: 'biznesmen yaniy - Sement , Megaton , Shifer , Qog\'oz va Avtobaza zavodlarini boshlig\'i .',
    bio: 'Abdulbori Muratov Namanganlik taniqli biznesmenlardan biri bo‘lib, o‘zining aql-zakovati, tejamkorligi va uzoqni ko‘ra bilishi bilan ajralib turadi. U SEMENT, MEGATON, SHIFER, QOG‘OZ va AVTOBAZA zavodlariga muvaffaqiyatli rahbarlik qilib, ularni eng ilg‘or korxonalar qatoriga olib chiqqan. Uning mehnati va fidoyiligi sabab ko‘plab medal hamda e’tiroflarga sazovor bo‘lgan.',
  },
  's10': {
    id: 's10',
    firstName: 'Muqaddasxon',
    lastName: 'Muratova',
    birthYear: 1965,
    gender: 'female',
    parents: [],
    children: ['11a', '11b', '11c', '11d', '11e'],
    spouses: ['10'],
    occupation: 'uy bekasi .',
    bio: 'Muqaddasxon Muratova Namanganlik oqila va saxovatli ayollardan biri sifatida tanilgan. U oilaparvarligi, dono fikrlashi va mehribon qalbi bilan atrofidagilarga doimo yaxshilik ulashib keladi. Uning saxiyligi va samimiyligi ko‘pchilik uchun ibrat bo‘lib, hayotga mehr va ezgulik bilan qarashga ilhom bag‘ishlaydi.',
  },
  '13': {
    id: '13',
    firstName: 'Masturaxon',
    lastName: 'Muratova',
    birthYear: 1964,
    gender: 'female',
    parents: ['3'],
    children: [],
    spouses: [],
    occupation: 'uy bekasi',
    bio: 'Masturaxon Muratova oilaparvar, pazanda va g‘amxo‘r ona sifatida xonadonining fayzi bo‘lib kelmoqda.',
  },
  '11a': {
    id: '11a',
    firstName: 'Abdurashid',
    lastName: 'Muratov',
    birthYear: 1984,
    gender: 'male',
    parents: ['10', 's10'],
    children: ['12a1', '12a2', '12a3', '12a4', '12a5'],
    spouses: ['s11a'],
    occupation: 'otasini ishini yurg\'izuvchisi .',
    bio: 'Abdurashid Muratov Namanganlik tajribali va mas’uliyatli rahbarlardan biri bo‘lib, 1984-yilda tavallud topgan. U otasi boshlab bergan ishlarni munosib davom ettirib, o‘zining oqilona boshqaruvi va mehnatsevarligi bilan katta yutuqlarga erishgan. Korxonalarni muvaffaqiyatli boshqargani sabab ko‘plab medal va e’tiroflarga sazovor bo‘lib, fidoyilik va qat’iyat timsoliga aylangan.'
  },
  's11a': {
    id: 's11a',
    firstName: 'Shaxnoza',
    lastName: 'Qayumova',
    birthYear: 1989,
    gender: 'female',
    parents: [],
    children: ['12a1', '12a2', '12a3', '12a4', '12a5'],
    spouses: ['11a'],
    occupation: 'uy bekasi .',
    bio: 'Shaxnoza Qayumova Namanganlik mehribon va g‘amxo‘r ayollardan biri sifatida tanilgan. U oilasiga bo‘lgan cheksiz mehri, samimiyligi va oqila fe’l-atvori bilan atrofidagilar qalbidan joy olgan. Uning sabr-toqati va ezgulikka boy hayot tarzi ko‘pchilikka mehr va insoniylikning haqiqiy qadrini his etishga ilhom bag‘ishlaydi.',
  },
  '12a1': {
    id: '12a1',
    firstName: 'Abdumajid',
    lastName: 'Muratov',
    birthYear: 2007,
    gender: 'male',
    parents: ['11a', 's11a'],
    children: [],
    spouses: [],
  },
  '12a2': {
    id: '12a2',
    firstName: 'Zulhayo',
    lastName: 'Muratova',
    birthYear: 2010,
    gender: 'female',
    parents: ['11a', 's11a'],
    children: [],
    spouses: [],
  },
  '12a3': {
    id: '12a3',
    firstName: 'Abdulaxad',
    lastName: 'Muratov',
    birthYear: 2012,
    gender: 'male',
    parents: ['11a', 's11a'],
    children: [],
    spouses: [],
  },
  '12a4': {
    id: '12a4',
    firstName: 'Abdulbosit',
    lastName: 'Muratov',
    birthYear: 2014,
    gender: 'male',
    parents: ['11a', 's11a'],
    children: [],
    spouses: [],
  },
  '12a5': {
    id: '12a5',
    firstName: 'Abdulloh',
    lastName: 'Muratov',
    birthYear: 2018,
    gender: 'male',
    parents: ['11a', 's11a'],
    children: [],
    spouses: [],
  },
  '11b': {
    id: '11b',
    firstName: 'Abdug\'affor',
    lastName: 'Muratov',
    birthYear: 1987,
    gender: 'male',
    parents: ['10', 's10'],
    children: ['12b1', '12b2', '12b3', '12b4'],
    spouses: ['s11b'],
    occupation: 'otasini ishini yurg\'izuvchisi.',
    bio: 'Abdug‘affor Muratov Namanganlik fidoyi va mas’uliyatli insonlardan biri bo‘lib, otasi boshlab bergan ishlarni munosib davom ettirib kelmoqda. U mehribonligi, g‘amxo‘rligi va oqilona boshqaruvi bilan atrofidagilar hurmatini qozongan. Mehnati va korxonalarni muvaffaqiyatli rivojlantirgani sabab ko‘plab medal hamda diplomlarga sazovor bo‘lib, qat’iyat va fidoyilik namunasi sifatida e’tirof etiladi.',
  },
  's11b': {
    id: 's11b',
    firstName: 'Firuzahon',
    lastName: 'Muhiddinova',
    birthYear: 1989,
    gender: 'female',
    parents: [],
    children: ['12b1', '12b2', '12b3', '12b4'],
    spouses: ['11b'],
    occupation: 'uy bekasi .',
    bio: 'Firuzahon Muhiddinova Namanganlik oqila va mehribon ayollardan biri sifatida tanilgan. U g‘amxo‘rligi, samimiyligi va dono fikrlashi bilan oilasi hamda atrofidagilar qalbidan chuqur joy olgan. Uning hayotga mehr va sabr bilan yondashuvi ko‘pchilikka ezgulik va insoniylik ulashib, ilhom bag‘ishlaydi.',
  },
  '12b1': {
    id: '12b1',
    firstName: 'Abdulaziz',
    lastName: 'Muratov',
    birthYear: 2007,
    gender: 'male',
    parents: ['11b', 's11b'],
    children: [],
    spouses: [],
  },
  '12b2': {
    id: '12b2',
    firstName: 'Abduraxim',
    lastName: 'Muratov',
    birthYear: 2010,
    gender: 'male',
    parents: ['11b', 's11b'],
    children: [],
    spouses: [],
  },
  '12b3': {
    id: '12b3',
    firstName: 'Madina',
    lastName: 'Muratova',
    birthYear: 2013,
    gender: 'female',
    parents: ['11b', 's11b'],
    children: [],
    spouses: [],
  },
  '12b4': {
    id: '12b4',
    firstName: 'Muslima',
    lastName: 'Muratova',
    birthYear: 2019,
    gender: 'female',
    parents: ['11b', 's11b'],
    children: [],
    spouses: [],
  },
  '11c': {
    id: '11c',
    firstName: 'Abduqodir',
    lastName: 'Muratov',
    birthYear: 1990,
    gender: 'male',
    parents: ['10', 's10'],
    children: ['12c1', '12c2', '12c3', '12c4'],
    spouses: ['s11c'],
    occupation: 'otasini ishini yurg\'izuvchisi.',
    bio: 'Abduqodir Muratov Namanganlik, mehribon va xushmuomala, mas’uliyatli insonlardan biri. U otasi boshlab bergan ishlarni davom ettirib, o‘z mehnati va fidoyiligi bilan muvaffaqiyatga erishgan. Korxonani samarali boshqargani uchun turli mukofot va medallarga sazovor bo‘lib, ibratli shaxs sifatida tanilgan.',
  },
  's11c': {
    id: 's11c',
    firstName: 'Zuxrahon',
    lastName: 'Abdurahimova',
    birthYear: 1991,
    gender: 'female',
    parents: [],
    children: ['12c1', '12c2', '12c3', '12c4'],
    spouses: ['11c'],
    occupation: 'uy bekasi .',
    bio: 'Zuxrahon Abdurahimova Namanganlik, mehribon va g‘amxo‘r uy bekasi sifatida oilasi va yaqinlari uchun doimo tayanch bo‘lib kelgan. U samimiyligi, sabr-toqati va oqila fazilatlari bilan atrofdagilar hurmatini qozongan. Oilasiga bo‘lgan cheksiz mehri va fidoyiligi bilan ko‘plab insonlarga iliqlik va ilhom ulashib kelmoqda.',
  },
  '12c1': {
    id: '12c1',
    firstName: 'Rahmatillo',
    lastName: 'Muratov',
    birthYear: 2009,
    gender: 'male',
    parents: ['11c', 's11c'],
    children: [],
    spouses: [],
  },
  '12c2': {
    id: '12c2',
    firstName: 'Muhammadsodiq',
    lastName: 'Muratov',
    birthYear: 2012,
    gender: 'male',
    parents: ['11c', 's11c'],
    children: [],
    spouses: [],
  },
  '12c3': {
    id: '12c3',
    firstName: 'Muhammadyusuf',
    lastName: 'Muratov',
    birthYear: 2013,
    gender: 'male',
    parents: ['11c', 's11c'],
    children: [],
    spouses: [],
  },
  '12c4': {
    id: '12c4',
    firstName: 'Ominahon',
    lastName: 'Muratova',
    birthYear: 2019,
    gender: 'female',
    parents: ['11c', 's11c'],
    children: [],
    spouses: [],
  },
  '11d': {
    id: '11d',
    firstName: 'Musohon',
    lastName: 'Muratov',
    birthYear: 1991,
    gender: 'male',
    parents: ['10', 's10'],
    children: ['12d1', '12d2', '12d3', '12d4', '12d5'],
    spouses: ['s11d'],
    occupation: 'otasini ishini yurg\'izuvchisi',
    bio: 'Musohon Muratov Namanganlik, aqlli va zehni kuchli insonlardan biri sifatida tanilgan. U otasi boshlab bergan ishlarni muvaffaqiyatli davom ettirib, o‘zining mehnatsevarligi va dono qarorlari bilan katta yutuqlarga erishgan. Fidoyiligi va intilishi tufayli oilaviy ishlarni yanada rivojlantirib, ko‘plab muvaffaqiyatlarga sababchi bo‘lgan ilhomlantiruvchi shaxslardan biridir.',
  },
  's11d': {
    id: 's11d',
    firstName: 'Oydinaxon',
    lastName: 'Sattarova',
    birthYear: 1993,
    gender: 'female',
    parents: [],
    children: ['12d1', '12d2', '12d3', '12d4', '12d5'],
    spouses: ['11d'],
    occupation: 'uy bekasi',
    bio: 'Oydinaxon Sattarova Namanganlik, g‘amxo‘r va aqlli uy bekasi sifatida oilasi va yaqinlari uchun doimo mehr ulashib kelayotgan insonlardan biri biridir. U o‘zining oqilaligi, sabr-toqati va samimiy munosabati bilan atrofdagilar hurmatini qozongan. Oilasiga bo‘lgan mehr-muhabbati va fidoyiligi bilan ko‘plab insonlarga ilhom bag‘ishlab kelmoqda.',
  },
  '12d1': {
    id: '12d1',
    firstName: 'Muhammadhon',
    lastName: 'Muratov',
    birthYear: 2013,
    gender: 'male',
    parents: ['11d', 's11d'],
    children: [],
    spouses: [],
  },
  '12d2': {
    id: '12d2',
    firstName: 'Bibioysha',
    lastName: 'Muratova',
    birthYear: 2015,
    gender: 'female',
    parents: ['11d', 's11d'],
    children: [],
    spouses: [],
  },
  '12d3': {
    id: '12d3',
    firstName: 'Nurmuxammad',
    lastName: 'Muratov',
    birthYear: 2017,
    gender: 'male',
    parents: ['11d', 's11d'],
    children: [],
    spouses: [],
  },
  '12d4': {
    id: '12d4',
    firstName: 'Muhammadsiddiq',
    lastName: 'Muratov',
    birthYear: 2020,
    gender: 'male',
    parents: ['11d', 's11d'],
    children: [],
    spouses: [],
  },
  '12d5': {
    id: '12d5',
    firstName: 'Sadiya',
    lastName: 'Muratova',
    birthYear: 2022,
    gender: 'female',
    parents: ['11d', 's11d'],
    children: [],
    spouses: [],
  },
  '11e': {
    id: '11e',
    firstName: 'Maryamhon',
    lastName: 'Muratova',
    birthYear: 1995,
    gender: 'female',
    parents: ['10', 's10'],
    children: ['12e1', '12e2', '12e3', '12e4'],
    spouses: ['s11e'],
    occupation: 'uy bekasi',
    bio: 'Maryamhon Muratova Namanganlik, g‘amxo‘r va sabrli uy bekasi sifatida oilasi va yaqinlari uchun doimo mehr va e’tibor ulashib kelayotgan insonlardan biridir. U o‘zining samimiyligi, sabr-toqati va oqila fazilatlari bilan atrofdagilar hurmatini qozongan. Oilasiga bo‘lgan cheksiz mehri va fidoyiligi bilan ko‘plab insonlarga ilhom bag‘ishlab kelmoqda.',
  },
  's11e': {
    id: 's11e',
    firstName: 'Raxmatillo',
    lastName: 'Babaxanov',
    birthYear: 1991,
    gender: 'male',
    parents: [],
    children: ['12e1', '12e2', '12e3', '12e4'],
    spouses: ['11e'],
    occupation: 'Tish do\'xtiri',
    bio: 'Raxmatillo Babaxanov Namanganlik, aqlli va chaqqon tish shifokori sifatida o‘z kasbiga bo‘lgan sadoqati bilan tanilgan. U professional mahorati, insonlarga bo‘lgan mehribon munosabati va tinimsiz mehnati orqali ko‘plab yutuqlarga erishgan. Malakali shifokor sifatida xalq ishonchini qozonib, o‘zining fidoyiligi va muvaffaqiyatlari bilan ko‘pchilikka ilhom bag‘ishlab kelmoqda.',
  },
  '12e1': {
    id: '12e1',
    firstName: 'Muhammadali',
    lastName: 'G\'iyasov',
    birthYear: 2013,
    gender: 'male',
    parents: ['11e', 's11e'],
    children: [],
    spouses: [],
  },
  '12e2': {
    id: '12e2',
    firstName: 'Xadicha',
    lastName: 'G\'iyasova',
    birthYear: 2015,
    gender: 'female',
    parents: ['11e', 's11e'],
    children: [],
    spouses: [],
  },
  '12e3': {
    id: '12e3',
    firstName: 'Muhammadamin',
    lastName: 'G\'iyasov',
    birthYear: 2017,
    gender: 'male',
    parents: ['11e', 's11e'],
    children: [],
    spouses: [],
  },
  '12e4': {
    id: '12e4',
    firstName: 'Ruqayya',
    lastName: 'G\'iyasova',
    birthYear: 2021,
    gender: 'female',
    parents: ['11e', 's11e'],
    children: [],
    spouses: [],
  },
};

export const MURATOV_GALLERY = [
  {
    id: 'g1',
    url: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?q=80&w=2070&auto=format&fit=crop',
    title: 'Katta Oila Jamlanmasi',
    year: 1980,
    description: 'Tursunbek bobo va Zahro buvilarimizning 50 yillik yubileylari.'
  },
  {
    id: 'g2',
    url: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=2070&auto=format&fit=crop',
    title: 'Qishloqdagi Hovli',
    year: 1955,
    description: 'Muratovlar sulolasi unib o\'sgan muqaddas hovli.'
  },
  {
    id: 'g3',
    url: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?q=80&w=2070&auto=format&fit=crop',
    title: 'Abdulla boboning yoshligi',
    year: 1962,
    description: 'Abdulla Muratov universitetni tamomlagan yillari.'
  }
];

export const MURATOV_HISTORY = [
  {
    id: 'h1',
    year: 2024,
    title: 'Oila Qadriyatlari va Hamjihatlik',
    content: 'Muratovlar sulolasi vakillari kuchli oilaviy rishtalar, bir-biriga bo‘lgan cheksiz mehr va ishonch bilan ajralib turadi. Ularning har bir a’zosi ajdodlar an’analarini davom ettirgan holda, oila obro‘sini yuksaltirishga intiladi.'
  },
  {
    id: 'h2',
    year: 2024,
    title: 'Ishbilarmonlik va Tadbirkorlik',
    content: 'Sulola vakillarida tadbirkorlik va mas’uliyat tuyg‘usi yuksak rivojlangan. Abdulbori Muratov va uning farzandlari tomonidan boshqarilayotgan korxonalar yurtimiz iqtisodiyoti rivojiga katta hissa qo‘shib kelmoqda.'
  },
  {
    id: 'h3',
    year: 2024,
    title: 'Ilm-ma\'rifat va Kasbiy Mahorat',
    content: 'Oilada ilmga bo‘lgan chanqoqlik va o‘z kasbidan zavqlanish asosiy fazilatlardan biridir. Shifokorlar, injenerlar va tadbirkorlar yetishib chiqqan bu sulola doimo yangilikka intilish va professional mahoratni oshirish bilan band.'
  },
  {
    id: 'h4',
    year: 2024,
    title: 'Oqilalik va Mehribonlik',
    content: 'Suloladagi ayollarning oqilaligi, sabr-toqati va xonadon fayzi uchun qilayotgan harakatlari barcha uchun ibratdir. Ularning g‘amxo‘rligi va dono maslahatlari oilaning mustahkam poydevori hisoblanadi.'
  }
];
