import { FamilyMember } from './types';

export const MURATOV_DATA: Record<string, FamilyMember> = {
  '1': {
    id: '1',
    firstName: 'Mahmudjon',
    lastName: 'xoji ota',
    birthYear: 1821,
    deathYear: 'Aniq emas',
    gender: 'male',
    parents: [],
    children: ['2'],
    spouses: [],
    bio: 'Muratovlar sulolasining ma\'lum bo\'lgan eng katta ajdodi.',
    occupation: 'Dehqon, Ma\'rifatparvar',
  },
  '2': {
    id: '2',
    firstName: 'Murodilloxon',
    lastName: 'xoji ota',
    birthYear: 1880,
    deathYear: 'Aniq emas',
    gender: 'male',
    parents: ['1'],
    children: ['3'],
    spouses: [],
    bio: 'Mahmudjon xoji otaning o\'g\'li.',
  },
  '3': {
    id: '3',
    firstName: 'Ergashali',
    lastName: 'xoji ota',
    birthYear: 1904,
    deathYear: 1995,
    gender: 'male',
    parents: ['2'],
    children: ['4'],
    spouses: [],
    occupation: 'Jamoat arbobi',
  },
  '4': {
    id: '4',
    firstName: 'Turdivoy',
    lastName: 'Muratov',
    birthYear: 1939,
    deathYear: 2002,
    gender: 'male',
    parents: ['3'],
    children: ['5'],
    spouses: [],
  },
  '5': {
    id: '5',
    firstName: 'Muhbubahon',
    lastName: 'Muratova',
    birthYear: 1945,
    deathYear: 2008,
    gender: 'female',
    parents: ['4'],
    children: ['6'],
    spouses: [],
  },
  '6': {
    id: '6',
    firstName: 'Habibahon',
    lastName: 'Ergashova',
    birthYear: 1950,
    deathYear: 2012,
    gender: 'female',
    parents: ['5'],
    children: ['7'],
    spouses: [],
  },
  '7': {
    id: '7',
    firstName: 'Nematjon',
    lastName: 'Muratov',
    birthYear: 1955,
    deathYear: 2022,
    gender: 'male',
    parents: ['6'],
    children: ['8'],
    spouses: [],
  },
  '8': {
    id: '8',
    firstName: 'Izzatilla',
    lastName: 'Muratov',
    birthYear: 1957,
    deathYear: 2020,
    gender: 'male',
    parents: ['7'],
    children: ['9'],
    spouses: [],
  },
  '9': {
    id: '9',
    firstName: 'Asadillo',
    lastName: 'Muratov',
    birthYear: 1959,
    gender: 'male',
    parents: ['8'],
    children: ['10'],
    spouses: [],
  },
  '10': {
    id: '10',
    firstName: 'Abdulbori',
    lastName: 'Muratov',
    birthYear: 1962,
    gender: 'male',
    parents: ['9'],
    children: ['11a', '11b', '11c', '11d', '11e'],
    spouses: [],
  },
  '11a': {
    id: '11a',
    firstName: 'Abdurashid',
    lastName: 'Muratov',
    birthYear: 1984,
    gender: 'male',
    parents: ['10'],
    children: [],
    spouses: ['s11a'],
  },
  's11a': {
    id: 's11a',
    firstName: 'Shaxnozahon',
    lastName: '',
    gender: 'female',
    parents: [],
    children: [],
    spouses: ['11a'],
    bio: 'Abdurashid Muratovning turmush o\'rtog\'i.',
  },
  '11b': {
    id: '11b',
    firstName: 'Abdug\'affor',
    lastName: 'Muratov',
    birthYear: 1995,
    gender: 'male',
    parents: ['10'],
    children: [],
    spouses: ['s11b'],
  },
  's11b': {
    id: 's11b',
    firstName: 'Firuzahon',
    lastName: '',
    gender: 'female',
    parents: [],
    children: [],
    spouses: ['11b'],
    bio: 'Abdug\'affor Muratovning turmush o\'rtog\'i.',
  },
  '11c': {
    id: '11c',
    firstName: 'Abduqodir',
    lastName: 'Muratov',
    birthYear: 1997,
    gender: 'male',
    parents: ['10'],
    children: [],
    spouses: ['s11c'],
  },
  's11c': {
    id: 's11c',
    firstName: 'Zuxrahon',
    lastName: '',
    gender: 'female',
    parents: [],
    children: [],
    spouses: ['11c'],
    bio: 'Abduqodir Muratovning turmush o\'rtog\'i.',
  },
  '11d': {
    id: '11d',
    firstName: 'Musohon',
    lastName: 'Muratov',
    birthYear: 1991,
    gender: 'male',
    parents: ['10'],
    children: [],
    spouses: ['s11d'],
  },
  's11d': {
    id: 's11d',
    firstName: 'Oydinahon',
    lastName: '',
    gender: 'female',
    parents: [],
    children: [],
    spouses: ['11d'],
    bio: 'Musohon Muratovning turmush o\'rtog\'i.',
  },
  '11e': {
    id: '11e',
    firstName: 'Maryamhon',
    lastName: 'Muratova',
    birthYear: 1995,
    gender: 'female',
    parents: ['10'],
    children: [],
    spouses: ['s11e'],
  },
  's11e': {
    id: 's11e',
    firstName: 'Raxmatillohon',
    lastName: '',
    gender: 'male',
    parents: [],
    children: [],
    spouses: ['11e'],
    bio: 'Maryamhon Muratovaning turmush o\'rtog\'i.',
  },
};

export const MURATOV_GALLERY = [
  {
    id: 'g1',
    url: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?q=80&w=2070&auto=format&fit=crop',
    title: 'Katta Oila Jamlanmasi',
    year: 1980,
    description: 'Tursunbek bobo va Zahro buvilarimizning 50 yillik yubileylari.'
  },
  {
    id: 'g2',
    url: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=2070&auto=format&fit=crop',
    title: 'Qishloqdagi Hovli',
    year: 1955,
    description: 'Muratovlar sulolasi unib o\'sgan muqaddas hovli.'
  },
  {
    id: 'g3',
    url: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?q=80&w=2070&auto=format&fit=crop',
    title: 'Abdulla boboning yoshligi',
    year: 1962,
    description: 'Abdulla Muratov universitetni tamomlagan yillari.'
  }
];

export const MURATOV_HISTORY = [
  {
    id: 'h1',
    year: 1910,
    title: 'Sulola Iptidodisi',
    content: 'Tursunbek Muratov Farg\'ona vodiysining chekka qishlog\'ida oddiy dehqon oilasida dunyoga kelgan. U o\'zining mehnatsevarligi va bilimga bo\'lgan ishtiyoqi bilan ajralib turgan.'
  },
  {
    id: 'h2',
    year: 1945,
    title: 'Muallimlik Davri',
    content: 'Urushdan keyingi yillarda Tursunbek bobo qishloq maktabida birinchi muallimlardan bo\'lib xizmat qila boshladi. U yuzlab shogirdlarga harf o\'rgatgan va ma\'rifat tarqatgan.'
  },
  {
    id: 'h3',
    year: 1990,
    title: 'Yuridik Meros',
    content: 'Muratovlar oilasi har doim halollik va ilm yo\'lini tanlashgan. Dunyo bo\'ylab tarqalgan avlodlar bugungi kunda turli sohalarda yurtimiz ravnaqi uchun xizmat qilmoqdalar.'
  }
];
